services:
  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FASTAPI_ENV=development
  selenium-hub:
    image: selenium/hub:4.21.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  robot-runner:
    build:
      context: ./robot
      dockerfile: Dockerfile
    volumes:
      - ./report/results:/app/results
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
    command: robot --outputdir /app/results /app/*.robot